name: Keep Streamlit App Alive
on:
  schedule:
    # 調整為 '0 16 * * *' 
    # UTC 時間 16:00 = 台灣時間隔天 00:00 (午夜)
    - cron: '0 16 * * *'
  workflow_dispatch: # 允許手動觸發測試

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: curl -I https://lrrwnorhkrxze5ujvwas6f.streamlit.app/
